using Microsoft.EntityFrameworkCore;
using ESEMS.Web.Data;
using ESEMS.Web.Models.Enums;
using ESEMS.Web.Models.Improvement;

namespace ESEMS.Web.Services.Improvements;

/// <summary>
/// Audit #16 — generates placeholder <see cref="ImprovementReview"/> rows on
/// the cadence defined by each <see cref="ReviewCycle"/>.
///
/// Polls every 12 hours. For every active cycle and every initiative
/// assigned to it, checks whether the next scheduled date has passed; if
/// yes, inserts an empty review (<c>HealthStatus = "Pending"</c>) for the
/// reviewer to fill in, then advances the assignment's
/// <c>LastGeneratedDate</c>.
///
/// Idempotent: multiple polls within the same cadence period are no-ops.
/// Skips initiatives that aren't in InProgress / OnHold (terminal states
/// don't need recurring reviews).
/// </summary>
public class RecurringReviewScheduler : BackgroundService
{
    private static readonly TimeSpan PollInterval = TimeSpan.FromHours(12);

    private readonly IServiceProvider _serviceProvider;
    private readonly ILogger<RecurringReviewScheduler> _logger;

    public RecurringReviewScheduler(
        IServiceProvider serviceProvider,
        ILogger<RecurringReviewScheduler> logger)
    {
        _serviceProvider = serviceProvider;
        _logger = logger;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        // BG-002 — distinguish "shut down cleanly" from "swallowed an
        // unrelated exception". Bare `catch { return; }` made silent shutdown
        // indistinguishable from a crash and lost the original exception in
        // the logs. OperationCanceledException is the *only* expected reason
        // Task.Delay throws here.
        try
        {
            await Task.Delay(TimeSpan.FromSeconds(75), stoppingToken);
        }
        catch (OperationCanceledException)
        {
            _logger.LogInformation("RecurringReviewScheduler cancelled during startup delay");
            return;
        }

        while (!stoppingToken.IsCancellationRequested)
        {
            try
            {
                await RunOnceAsync(stoppingToken);
            }
            catch (OperationCanceledException) when (stoppingToken.IsCancellationRequested)
            {
                break;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Recurring-review scheduler sweep failed");
            }

            try
            {
                await Task.Delay(PollInterval, stoppingToken);
            }
            catch (OperationCanceledException)
            {
                _logger.LogInformation("RecurringReviewScheduler cancelled during inter-cycle delay");
                break;
            }
        }
    }

    private async Task RunOnceAsync(CancellationToken ct)
    {
        using var scope = _serviceProvider.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();

        var now = DateTime.UtcNow;

        var assignments = await db.Set<ImprovementReviewCycleAssignment>()
            .Include(a => a.ReviewCycle)
            .Include(a => a.Improvement)
            .Where(a => a.ReviewCycle != null
                        && a.ReviewCycle.IsActive
                        && a.ReviewCycle.StartDate <= now
                        && (a.ReviewCycle.EndDate == null || a.ReviewCycle.EndDate >= now)
                        && a.Improvement != null
                        && !a.Improvement.IsDeleted
                        && (a.Improvement.Status == ImprovementStatus.InProgress
                            || a.Improvement.Status == ImprovementStatus.OnHold))
            .ToListAsync(ct);

        if (assignments.Count == 0) return;

        // Suspend the change-log interceptor — these are system-driven inserts.
        using var _ = SuspendImprovementChangeLog.Begin();

        var added = 0;
        foreach (var a in assignments)
        {
            if (ct.IsCancellationRequested) return;

            var lastDate = a.LastGeneratedDate ?? a.ReviewCycle!.StartDate;
            var nextDue = AdvanceBy(lastDate, a.ReviewCycle!.Cadence);
            if (nextDue > now) continue;

            db.Set<ImprovementReview>().Add(new ImprovementReview
            {
                ImprovementId = a.ImprovementId,
                ReviewDate = now,
                HealthStatus = "Pending",
                NotesEn = $"Auto-generated by '{a.ReviewCycle.Name}' cycle. Awaiting reviewer input.",
                NotesAr = $"تم إنشاؤه تلقائياً بواسطة دورة '{a.ReviewCycle.NameAr ?? a.ReviewCycle.Name}'. في انتظار المراجع.",
                NextReviewDate = AdvanceBy(now, a.ReviewCycle.Cadence),
                CreatedAt = now
            });
            a.LastGeneratedDate = now;
            added++;
        }

        if (added > 0)
        {
            await db.SaveChangesAsync(ct);
            _logger.LogInformation("RecurringReviewScheduler: created {Count} placeholder review(s)", added);
        }
    }

    private static DateTime AdvanceBy(DateTime baseDate, ReviewCadence cadence) => cadence switch
    {
        ReviewCadence.Monthly      => baseDate.AddMonths(1),
        ReviewCadence.Quarterly    => baseDate.AddMonths(3),
        ReviewCadence.SemiAnnually => baseDate.AddMonths(6),
        ReviewCadence.Annually     => baseDate.AddYears(1),
        _                          => baseDate.AddMonths(3)
    };
}
