using ESEMS.Web.Models.Common;
using ESEMS.Web.Models.Enums;

namespace ESEMS.Web.Models.APQC;

/// <summary>
/// APQC Level 1 - Category
/// High-level grouping of related business areas
/// </summary>
public class Category : AuditableBilingualEntity
{
    /// <summary>
    /// Category code — plain integer in the new hierarchical scheme (e.g., "1", "2").
    /// Auto-generated by the controller; not user-editable.
    /// </summary>
    public string Code { get; set; } = string.Empty;

    /// <summary>
    /// Zero-padded version of Code for natural lexicographic sort
    /// (e.g. "1" → "0001", "10" → "0010"). Set by the migration / generator.
    /// </summary>
    public string? SortKey { get; set; }

    /// <summary>
    /// Multiple configurable tags (comma-separated)
    /// </summary>
    public string? Tags { get; set; }

    /// <summary>
    /// Aggregated total duration in minutes from child process groups
    /// </summary>
    public decimal? AggregatedDurationMinutes { get; set; }

    /// <summary>
    /// Aggregated total cost from child process groups
    /// </summary>
    public decimal? AggregatedCost { get; set; }

    /// <summary>
    /// Whether this category contains automated processes
    /// </summary>
    public bool HasAutomatedProcesses { get; set; }

    // Navigation properties
    public ICollection<ProcessGroup> ProcessGroups { get; set; } = new List<ProcessGroup>();

    /// <summary>
    /// Gets the list of tags
    /// </summary>
    public List<string> GetTagList()
    {
        if (string.IsNullOrEmpty(Tags))
            return new List<string>();
        return Tags.Split(',', StringSplitOptions.RemoveEmptyEntries)
                   .Select(t => t.Trim())
                   .ToList();
    }

    /// <summary>
    /// Sets tags from a list
    /// </summary>
    public void SetTagList(IEnumerable<string> tags)
    {
        Tags = string.Join(",", tags.Where(t => !string.IsNullOrWhiteSpace(t)));
    }
}

