using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ESEMS.Web.Models.Improvement;

/// <summary>
/// Cadence at which a <see cref="ReviewCycle"/> generates placeholder
/// reviews on its assigned initiatives.
/// </summary>
public enum ReviewCadence
{
    Monthly,
    Quarterly,
    SemiAnnually,
    Annually
}

/// <summary>
/// Audit #16 — DGEP 4G Stage-Gate Governance §3.2.
///
/// Defines a recurring stage-gate review schedule that an executive
/// committee owns. Today every <see cref="ImprovementReview"/> is a
/// one-off snapshot with no parent schedule — the audit's gap was that
/// "every initiative has reviews" but "nobody owns the calendar of when
/// reviews should happen on which initiative."
///
/// A ReviewCycle answers that:
///   - <see cref="Cadence"/> says how often (monthly / quarterly / etc.).
///   - <see cref="OwningCommittee"/> says who chairs it.
///   - <see cref="StartDate"/> anchors the schedule.
///   - The recurring-review scheduler (<c>RecurringReviewScheduler</c>
///     background service) generates one placeholder
///     <see cref="ImprovementReview"/> row per assigned initiative per
///     cadence period, ready for the reviewer to fill in.
///
/// Initiatives opt-in to a cycle via <see cref="ImprovementReviewCycleAssignment"/>
/// (M2M). One cycle can cover many initiatives; one initiative can sit in
/// multiple cycles (e.g. monthly Owner check + quarterly Steering review).
/// </summary>
[Table("ReviewCycles")]
public class ReviewCycle
{
    [Key]
    public string Id { get; set; } = Guid.NewGuid().ToString();

    [Required, MaxLength(150)]
    public string Name { get; set; } = string.Empty;

    [MaxLength(150)]
    public string? NameAr { get; set; }

    public ReviewCadence Cadence { get; set; } = ReviewCadence.Quarterly;

    /// <summary>
    /// Free-text committee name (e.g. "PMO Steering Committee", "Innovation
    /// Council"). Not an FK because committees are loosely defined and
    /// often span multiple OrganizationUnits.
    /// </summary>
    [MaxLength(200)]
    public string? OwningCommittee { get; set; }

    /// <summary>
    /// First scheduled review date. The scheduler computes subsequent dates
    /// by adding cadence periods.
    /// </summary>
    public DateTime StartDate { get; set; } = DateTime.UtcNow.Date;

    /// <summary>
    /// Optional end date. After this point the scheduler stops generating
    /// new placeholder reviews for this cycle.
    /// </summary>
    public DateTime? EndDate { get; set; }

    public bool IsActive { get; set; } = true;

    [MaxLength(1000)]
    public string? Notes { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    // Navigation
    public ICollection<ImprovementReviewCycleAssignment> Assignments { get; set; }
        = new List<ImprovementReviewCycleAssignment>();
}

/// <summary>
/// M2M assignment between <see cref="ImprovementInitiative"/> and
/// <see cref="ReviewCycle"/>. Tracks the last-generated date so the
/// scheduler doesn't double-create reviews when it polls.
/// </summary>
[Table("ImprovementReviewCycleAssignments")]
public class ImprovementReviewCycleAssignment
{
    [Key]
    public string Id { get; set; } = Guid.NewGuid().ToString();

    [Required]
    public string ImprovementId { get; set; } = string.Empty;

    [Required]
    public string ReviewCycleId { get; set; } = string.Empty;

    /// <summary>
    /// Most recent review date generated by the scheduler for this pair.
    /// The next placeholder is created when <c>now &gt;= LastGeneratedDate + Cadence</c>.
    /// </summary>
    public DateTime? LastGeneratedDate { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // Navigation
    [ForeignKey(nameof(ImprovementId))]
    public ImprovementInitiative? Improvement { get; set; }

    [ForeignKey(nameof(ReviewCycleId))]
    public ReviewCycle? ReviewCycle { get; set; }
}
